import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { CartProvider } from '@/context/CartContext'; // Import the CartProvider
import TranslationsProvider from "@/components/TranslationsProvider";
import initTranslations from "../i18n"; // Import translations initialization
import { logo2 } from "@/public";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children, params: { locale } }) => {
  const i18nNamespaces = ["navbar", "home", "categories", "diseases", 'sleepDisorders', 'respiratoryFailure']; // Add relevant namespaces
  const { resources } = await initTranslations(locale, i18nNamespaces); // Initialize translations

  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <CartProvider> {/* Wrap with CartProvider */}
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            <Navbar />
            {children}
            <Footer />
          </TranslationsProvider>
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
